apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-microservice      # must match your Helm release’s Deployment name
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

